services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./:/app/temp-src
      - /app/vt-app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCH_SRC=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true